### ISSUE TITLE
Create your own API if needed? Current one broke down.

### ISSUE THREAD

**Issue by Skyridr** [akaminetzkyp/royale-stats#3]
It appears that the API this system is using is down:

http://api.cr-api.com

Which breaks this system:

> INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.cr-api.com
Traceback (most recent call last):
  File "/main.py", line 13, in <module>
    logger = Logger(clan_tag)
  File "/logger.py", line 10, in __init__
    self.wrapper = Wrapper(clan_tag)
  File "/api_wrapper.py", line 9, in __init__
    self.update_data()
  File "/api_wrapper.py", line 13, in update_data
    self.data = requests.get(self.url).json()
  File "/models.py", line 812, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Maybe optional to use your own API that this system supports? 

Something like this: https://github.com/martincarrera/clash-royale-api

So if an external API breaks down, you can always choose to use your own internal API.

btw, if an API is down, the system should print it can't reach the API ^^.

Regards,
Skyrider

**Comment by kaminetzky** [comment]
Hello Skyrider! Thank you very much for your feedback! I'll fix this bug as soon as possible.

The API is down. A fix is expected in a few hours.

Regards,
Alejandro
